---
version: "3"

volumes:
  workdir:
    driver: local
  confdir:
    driver: local

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      - 80:80/tcp
      - 853:853/tcp
      - 3000:3000/tcp
    volumes:
      - workdir:/opt/adguardhome/work
      - confdir:/opt/adguardhome/conf
    restart: unless-stopped